### ISSUE TITLE
LGPL License Complications

### ISSUE THREAD

**Issue by chadefranklin** [ricardojmendez/LibNoise.Unity#18]
Hello, I was looking into using LibNoise.Unity for a project I'm working on, but from my limited research, it seems the LGPL license brings some complications when used in conjunction with Unity as users may build for platforms that require a single executable that doesn't allow for a separate DLL. This would force users' entire codebase to be LGPL, not just the LibNoise.Unity Library. Is this intended? Furthermore, the repo is not provided as a DLL, to begin with, which may mean All projects using LibNoise.Unity must be fully open-sourced under the LGPL license. Is this also intended? If not, is LGPL the best license for this project, or could I and others be misunderstanding the LGPL license?

Here is some more info:
https://www.gnu.org/licenses/gpl-faq.en.html#LGPLStaticVsDynamic
https://github.com/jderrough/UnitySlippyMap/issues/20
https://github.com/ajman1101/Twine2Unity/issues/12
https://forum.unity.com/threads/gnu-gpl-3-open-source-license-and-unity-question.590035/

**Comment by ricardojmendez** [comment]
LibNoise.Unity is a port of LGPL code, and as such it must remain LGPL'd. Changing the license now would also require getting past contributors to agree to the change, since they contributed their code under this license.

I'm sorry to say that a change is highly unlikely.

**Comment by chadefranklin** [comment]
I see, thanks for your response.
